# Generated by Django 4.2 on 2023-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortapp', '0002_alter_containertype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyser',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sortarea',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
