# Generated by Django 4.2 on 2023-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortapp', '0003_alter_analyser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='dead_volume',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sma_id',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='test_volume',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
