# Generated by Django 4.2 on 2023-06-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortapp', '0004_alter_analysis_dead_volume_alter_analysis_sma_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='lih_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sma_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
