# Generated by Django 4.2 on 2023-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortapp', '0005_alter_analysis_lih_flag_alter_analysis_sma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='sma_id',
            field=models.PositiveIntegerField(blank=True, default='Null', null=True, unique=True),
        ),
    ]
