# Generated by Django 4.2 on 2023-06-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortapp', '0006_alter_analysis_sma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='dead_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='test_volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
